version: 2.1
orbs:
  architect: giantswarm/architect@0.4.3

jobs:
  checkout_code:
    docker:
      - image: circleci/golang
    working_directory: ~/giantswarm-todo
    steps:
      - checkout
      - run: pwd && ls -la
      - run: mkdir ~/bin && curl -sL https://github.com/giantswarm/architect/releases/download/0e9225d/architect -o ~/bin/architect && chmod +x ~/bin/architect
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/giantswarm-todo
      - save_cache:
          key: architect
          paths:
            - ~/bin
  build_apiserver:
    machine: true
    working_directory:
      ~/giantswarm-todo/api-server
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: architect
      - run: architect project version
      - run: IMG_VER=$(architect project version) make docker-build
      - run: echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io 
      - run: IMG_VER=$(architect project version) make docker-push
  build_todomanager:
    machine: true
    working_directory:
      ~/giantswarm-todo/todo-manager
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: architect
      - run: architect project version
      - run: IMG_VER=$(architect project version) make docker-build
      - run: echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io 
      - run: IMG_VER=$(architect project version) make docker-push
workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - build_apiserver:
          requires:
            - checkout_code
      - build_todomanager:
          requires:
            - checkout_code
  
