version: 2.1
orbs:
  architect: giantswarm/architect@0.8.5

jobs:
  checkout_code:
    machine: true
    working_directory: ~/giantswarm-todo
    steps:
      - checkout
      - run: docker run -v $(pwd):/workdir --workdir /workdir --rm quay.io/giantswarm/architect:latest project version > api-server/.version
      - run: cat api-server/.version
      - run: cp api-server/.version todo-manager/
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
          paths:
            - ~/giantswarm-todo
  build_apiserver:
    machine: true
    working_directory:
      ~/giantswarm-todo/api-server
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
      - run: cat .version
      - run: IMG_VER=$(cat .version) make docker-build
      - run: echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io 
      - run: IMG_VER=$(cat .version) make docker-push
  build_todomanager:
    machine: true
    working_directory:
      ~/giantswarm-todo/todo-manager
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
      - run: cat .version
      - run: IMG_VER=$(cat .version) make docker-build
      - run: echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io 
      - run: IMG_VER=$(cat .version) make docker-push
  run_tests:
    machine: true
    working_directory:
      ~/giantswarm-todo/todo-manager
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
      - run: wget -q https://github.com/giantswarm/kind-app-testing/raw/master/kind-app-testing.sh -o /usr/local/bin/kind-app-testing.sh
      - run: chmod +x /usr/local/bin/kind-app-testing.sh
      - run: kind-app-testing.sh -c giantswarm-todo-app
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results    


workflows:
  version: 2
  build:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /^v.*/
      - build_apiserver:
          requires:
            - checkout_code
          filters:
            tags:
              only: /^v.*/
      - build_todomanager:
          requires:
            - checkout_code
          filters:
            tags:
              only: /^v.*/
      - run_tests:
          name: "run kind-app-testing"
          requires:
            - build_apiserver
            - build_todomanager
          filters:
            tags:
              only: /^v.*/
