version: 2.1
orbs:
  architect: giantswarm/architect@0.4.3

jobs:
  checkout_code:
    docker:
      - image: circleci/golang
    working_directory: ~/giantswarm-todo
    steps:
      - checkout
      - run: pwd && ls -la
      - run: mkdir ~/bin && curl -sL https://github.com/giantswarm/architect/releases/download/0e9225d/architect -o ~/bin/architect && chmod +x ~/bin/architect
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/giantswarm-todo
      - save_cache:
          key: architect
          paths:
            - ~/bin
  build_apiserver:
    machine: true
    working_directory:
      ~/giantswarm-todo/api-server
    steps:
      - run: echo "export PATH=$PATH:~/bin >> $BASH_ENV"
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: apiserver-gomodules-cache-{{ checksum "~/giantswarm-todo/api-server/go.sum" }}
      - restore_cache:
          key: architect
      - run: echo $PATH && ls -la 
      - run: architect project version
      - run: make docker-build
      - run: echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io 
      - run: make docker-push
      - save_cache:
          key: apiserver-gomodules-cache-{{ checksum "~/giantswarm-todo/api-server/go.sum" }}
          paths:
            - ${GOPATH}/pkg/mod
workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - build_apiserver:
          requires:
            - checkout_code
  
