version: 2.1
orbs:
  architect: giantswarm/architect@0.8.9

jobs:
  checkout_code:
    machine: true
    working_directory: ~/giantswarm-todo
    steps:
      - checkout
      - run: docker run -v $(pwd):/workdir --workdir /workdir --rm quay.io/giantswarm/architect:latest project version > api-server/.version
      - run: cat api-server/.version
      - run: cp api-server/.version todo-manager/
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
          paths:
            - ~/giantswarm-todo
  build_apiserver:
    machine: true
    working_directory:
      ~/giantswarm-todo/api-server
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
      - run: cat .version
      - run: IMG_VER=$(cat .version) make docker-build
      - run: echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io 
      - run: IMG_VER=$(cat .version) make docker-push
  build_todomanager:
    machine: true
    working_directory:
      ~/giantswarm-todo/todo-manager
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
      - run: cat .version
      - run: IMG_VER=$(cat .version) make docker-build
      - run: echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io 
      - run: IMG_VER=$(cat .version) make docker-push

workflows:
  version: 2
  build:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /^v.*/
      - build_apiserver:
          requires:
            - checkout_code
          filters:
            tags:
              only: /^v.*/
      - build_todomanager:
          requires:
            - checkout_code
          filters:
            tags:
              only: /^v.*/
      - architect/run-kat-tests:
          name: "run kat tests"
          chart: "giantswarm-todo-app"
          requires:
            - build_apiserver
            - build_todomanager
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          name: "package and push giantswarm-todo-app chart"
          requires:
            - "run kat tests"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "giantswarm-todo-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
