---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: todo-role
  namespace: todo
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - todo-psp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todo-rolebinding
  namespace: todo
roleRef:
  kind: Role
  name: todo-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
