---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apiserver
  namespace: todo
  labels:
    app: apiserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      serviceAccountName: apiserver
      containers:
        - name: apiserver
          image: "apiserver:latest"
          imagePullPolicy: "Never"
          env:
            - name: "TODO_URL"
              value: "todomanager:8090"
          ports:
            - name: rest
              containerPort: 8080
              protocol: TCP
          resources:
            {}
            
