---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "giantswarm-todo.apiserver.labels" . | indent 4 }}
spec:
  type: {{ .Values.apiserverServiceType }}
  selector:
{{ include "giantswarm-todo.apiserver.match-labels" . | indent 4 }}
  ports:
    - name: rest
      port: 8080
      protocol: TCP
      targetPort: 8080
