apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}-todo-psp
  labels:
{{ include "giantswarm-todo.labels" . | indent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: true
  allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
    - NET_BIND_SERVICE
  requiredDropCapabilities:
    - ALL
  fsGroup:
    rule: MustRunAs
    ranges:
    - max: 65535
      min: 1
  runAsGroup:
    rule: MustRunAs
    ranges:
    - max: 65535
      min: 1
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  volumes:
  - secret
  - emptyDir
  - configMap

