apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: todomanager-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "giantswarm-todo.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "giantswarm-todo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: apiserver
    ports:
    - protocol: TCP
      port: 8090
  - from:
    - namespaceSelector:
        matchLabels:
          linkerd.io/control-plane-ns: {{ .Values.linkerdNamespace }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: todo-mysql
    ports:
    - protocol: TCP
      port: 3306
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          linkerd.io/control-plane-ns: {{ .Values.linkerdNamespace }}
