---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: todomanager-pdb
  namespace: {{ .Release.Name }}
  labels:
{{ include "giantswarm-todo.labels" . | indent 4 }}
spec:
  minAvailable: 70%
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "giantswarm-todo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
