apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: todomanager-network-policy
  namespace: {{ .Values.namespace }}
  labels:
{{- include "giantswarm-todo.todomanager.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "giantswarm-todo.todomanager.match-labels" . | indent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
{{ include "giantswarm-todo.apiserver.match-labels" . | indent 10 }}
    ports:
    - protocol: TCP
      port: 8090
  - from:
{{ include "giantswarm-todo.netpol.linkerd" . | indent 4 }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: todo-mysql
    ports:
    - protocol: TCP
      port: 3306
  - to:
{{ include "giantswarm-todo.netpol.kube-dns" . | indent 4 }}
  - to:
{{ include "giantswarm-todo.netpol.linkerd" . | indent 4 }}
